apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: 187472738026.dkr.ecr.us-east-1.amazonaws.com/node-js:master-7e558f9ab7d65d33fe10f3a53ab356153a4dd20d
          ports:
            - containerPort: 8080
